
const GET_SELLER="GET_SELLER"
const SHOW_DETAIL="SHOW_DETAIL"
const SHOW_DETAILALL="SHOW_DETAILALL"
const HIDE_DETAIL="HIDE_DETAIL"
const GET_GOODS='GET_GOODS';
const HIDE_DETAILALL="HIDE_DETAILALL"
const GET_RATINGS='GET_RATINGS'
const GET_SELLERS='GET_SELLERS'
const GET_SELLERALL='GET_SELLERALL'
const SHOW_DETAILSELECT="SHOW_DETAILSELECT"
const FOOD_SHOW = 'FOOD_SHOW'
const HIDE_DETAILSELECT="HIDE_DETAILSELECT"
const GET_ARR="GET_ARR"
//评论选择列表
const SELECT='SELECT'
//初始化
const CHANGE_TYPES='CHANGE_TYPES'
//查看有内容的时候
const TOGGLE='TOGGLE'
 const SHOW_FOOD='SHOW_FOOD';
 const HIDE_FOOD='HIDE_FOOD';

export default {
	GET_SELLER,
	GET_SELLERALL,
	SHOW_DETAIL,
	SHOW_DETAILALL,
	HIDE_DETAIL,
	HIDE_DETAILALL,
	SHOW_DETAILSELECT,
	HIDE_DETAILSELECT,
	SELECT,
	GET_GOODS,
	GET_RATINGS,
	GET_SELLERS,
	GET_SELLERALL,
	GET_ARR,
	SHOW_FOOD,
	HIDE_FOOD,
	TOGGLE,
	FOOD_SHOW

}